# Generated by Django 3.2.8 on 2021-10-29 13:03

from django.db import migrations, models
import msukwini.core.posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.CharField(max_length=11)),
                ('image1', models.ImageField(upload_to=msukwini.core.posts.models.upload_to)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=msukwini.core.posts.models.upload_to)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=msukwini.core.posts.models.upload_to)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=msukwini.core.posts.models.upload_to)),
                ('image5', models.ImageField(blank=True, null=True, upload_to=msukwini.core.posts.models.upload_to)),
                ('image6', models.ImageField(blank=True, null=True, upload_to=msukwini.core.posts.models.upload_to)),
                ('description', models.TextField(blank=True, null=True)),
                ('headline', models.CharField(max_length=140)),
                ('datetime_created', models.DateTimeField(auto_now_add=True)),
                ('date_create', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
